
simulation:
  grid_size: [30, 30]
  day_length: 240
  max_ticks: 580
  num_agents: 30

agent: 
  # Default values
  name: "A0"
  home: "home_0"
  workplace: "workplace_0"
  income: 5             # WARNING: UNUSED 
  social_tolerance: 3  # WARNING: UNUSED 
  
  # Constants
  energy_capacity: 20 # WARNING: UNUSED 
  
houses:
  home_0: [1, 1]

workplace_locations:
  workplace_0: [36, 36] # TODO: pick from map
  workplace_1: [36, 36]
  workplace_2: [36, 36]

policy:
  workplace_0: "fixed"
  workplace_1: "free"
  workplace_2: "flex" # allow to go to work at anytime
  #workplace_2: "flex_2" # trailing number indicates flexible hours (NOT IMPLEMENTED)

